apiVersion: workflows.dev/v1alpha1
kind: TemplateInstance
metadata:
  namespace: pipelines
spec:
  templateName: clojure-service-sachem-i18n
  inputFrom:
    - name: sachem
      valueFrom:
        configMapKeyRef:
          name: services-sachem
          key: ganho-capital
  input:
    sachem-params:
      runOnMaster: "true"
      runOnPullRequests: "true"
      resources:
        cpu: 8
        memory: 4Gi
